### ISSUE TITLE
suspicious 406 on validate

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#69]
```
# curl -i -X PUT https://demo.netwerkdigitaalerfgoed.nl/register-api/datasets/validate \
   -H 'link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type",<http://www.w3.org/ns/ldp#Resource>; rel="type"' \   
   -H 'content-type: application/ld+json' \
   --data-binary '{"@id":"https://data.stad.gent/explore/dataset/vondelingen/information/"}'

HTTP/2 406
date: Sat, 20 Feb 2021 00:28:44 GMT
content-type: text/plain; charset=utf-8
content-length: 45
strict-transport-security: max-age=15724800; includeSubDomains

Unexpected "\n" at position 193 in state STOP


# shacl validate --shapes shapes.jsonld --data data.jsonld

@prefix schema: <http://schema.org/> .
@prefix void:  <http://rdfs.org/ns/void#> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dctype: <http://purl.org/dc/dcmitype/> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcat:  <http://www.w3.org/ns/dcat#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  []  ;
                 sh:resultMessage              "minCount[1]: Invalid cardinality: expected min 1: Got count = 0" ;
                 sh:resultPath                 schema:creator ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:MinCountConstraintComponent ;
                 sh:sourceShape                []
               ]
] .

```

**Comment by ddeboer** [comment]
This is an internal Comunica error, which you can reproduce by querying that URL with Comunica directly:

```
comunica-sparql https://data.stad.gent/explore/dataset/vondelingen/information/  "SELECT * WHERE { ?s ?p ?o }"
[(node:20605) UnhandledPromiseRejectionWarning: Error: Unexpected "\n" at position 193 in state STOP
    at Function.newErrorCoded (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-parse-html-script/lib/HtmlScriptListener.js:33:23)
    at JsonLdParser.<anonymous> (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/@comunica/actor-rdf-parse-html-script/lib/HtmlScriptListener.js:86:26)
    at JsonLdParser.emit (events.js:327:22)
    at Parser.jsonParser.onError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:370:18)
    at Parser.proto.charError (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonparse/jsonparse.js:90:8)
    at Parser.proto.write (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonparse/jsonparse.js:199:23)
    at JsonLdParser._transform (/usr/local/lib/node_modules/@comunica/actor-init-sparql/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:110:25)
    at JsonLdParser.Transform._read (internal/streams/transform.js:205:10)
    at JsonLdParser.Transform._write (internal/streams/transform.js:193:12)
    at doWrite (internal/streams/writable.js:377:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
(node:20605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is not something we can fix on our side, so please report at Comunica.

**Comment by coret** [comment]
Done https://github.com/comunica/comunica/issues/785

**Comment by coret** [comment]
(Deel van de ) reactie van de Technisch applicatiespecialist Web van District09:
> Correct, blijkbaar parsed ons portaal die newlines er niet uit voor de JSON-LD info.
> Bedankt om dit door te geven, ik neem het even op met de leverancier om dit te bekijken.
> Ondertussen heb ik voor deze set de omschrijving aangepast en alle newlines er uit gehaald.

Dus, de JSON-LD van de dataset is valide qua syntaxis (inhoudelijk mist er een creator), **echter** de API geeft een 406 (zonder foutmelding)?

**Comment by ddeboer** [comment]
406 means no dataset found, which is correct because the JSON-LD contains no IRI (`@id`):

```json
 {
        "@context":"http://schema.org/",
        "@type":"Dataset",
        "name":"Vondelingen register Gent",
        "description":"De registers van de vondelingen maken deel uit van de archieven van de Commissie van Burgerlijke Godshuizen. Elke bladzijde in deze registers is een soort persoonlijk dossier van de vondeling waarop verschillende gegevens terug te vinden zijn: naam, (vermoedelijke) geboortedatum en leeftijd, vindplaats... Er stond ook meestal wat er met het kind gebeurd was nadat het gevonden werd: overleden, geplaatst bij een voedster, terug naar de moeder... ",
        "url":"https://data.stad.gent/explore/dataset/vondelingen/",
        "dateModified": "2020-06-15T15:49:53.187480+00:00"
        ,
        "keywords": ["vondelingen"]
        
    ,
        "distribution": [
        
            {
                "@type":"DataDownload",
                "encodingFormat":"CSV",
                "contentUrl":"https://data.stad.gent/explore/dataset/vondelingen/download?format=csv"
            },
        
            {
                "@type":"DataDownload",
                "encodingFormat":"JSON",
                "contentUrl":"https://data.stad.gent/explore/dataset/vondelingen/download?format=json"
            },
        
            {
                "@type":"DataDownload",
                "encodingFormat":"Excel",
                "contentUrl":"https://data.stad.gent/explore/dataset/vondelingen/download?format=xls"
            }
        
        ]
    
    ,
    "license": "https://overheid.vlaanderen.be/modellicentie-gratis-hergebruik"
    
    }
```

**Comment by coret** [comment]
We (now :-) require an IRI, but the https://data.stad.gent/explore/dataset/vondelingen/information/ does contain a dataset, it's just that one of _our_ requirements is not met. 

Why say it's not valid because schema:creator is missing but say "no dataset found" when a IRI is missing? 
If we also add the IRI requirement to the SHACL, will we then get a validation error for the missing IRI?

**Comment by ddeboer** [comment]
I don’t think you can add the IRI requirement to the SHACL (because it’s about the subject, not about the predicates/objects), but you can try.
